name = "qms-system"
main = ".open-next/worker.js"
compatibility_date = "2025-05-20"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[env.production]
name = "qms-system-prod"

[env.staging]
name = "qms-system-staging"
